name: 'microsoft_connectors'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'microsoft'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  microsoft_connectors:
    # Config indicated by + and applies to all files under models/microsoft/
    microsoft:
      +materialized: table

# Define variables here
vars:
  ad_history_identifier: ad_history
  account_history_identifier: account_history
  campaign_history_identifier: campaign_history
  keyword_history_identifier: keyword_history
  ad_group_history_identifier: ad_group_history
  ad_performance_daily_report_identifier: ad_performance_daily_report
  goals_and_funnels_daily_report_identifier: goals_and_funnels_daily_report
  keyword_performance_daily_report_identifier: keyword_performance_daily_report
  campaign_performance_daily_report_identifier: campaign_performance_daily_report
  campaign_impression_performance_daily_report_identifier: campaign_impression_performance_daily_report
  destination_url_performance_daily_report_identifier: destination_url_performance_daily_report

